# Modelos de ejecución asíncrona

Como vimos anteriormente la diferencia entre paralelismo y concurrencia es
sutil pero relevante: la **concurrencia se produce cuando más de una tarea
progresa al mismo tiempo**, sin esperar las unas a la finalización de las
otras. El **paralelismo se produce cuando dos tareas se ejecutan al mismo
tiempo**.

La asincronía es una forma de concurrencia, pero no de paralelismo, que, en
Python y JavaScript es colaborativa. A lo largo de esta lección usaremos
**JavaScript** para mostrar la historia de los modelos de ejecución asíncrona.

JavaScript fue diseñado con la asincronía en el corazón de su modelo de
ejecución y resulta más sencilla de entender en este lenguaje.

Prepara una carpeta con los siguientes ficheros, inicia un servidor estático
y utilizar la consola de depuración de un navegador cualquiera para
probar el código:

```
.
└── index.html
```

Dentro de `index.html`, añade:

```html
<p>Hola mundo</p>
```

E inicia el servidor estático:

```bash
$ python -m http.server
```

## _Callbacks_ y paso de continuidad

Un _callback_ es una función que se pasa a un procedimiento para que sea
llamada tras la finalización del mismo. El _callback_ lo utiliza una API
para avisar de que algo ha terminado:

```js
var xhr = new XMLHttpRequest();
xhr.onload = evt => console.log(evt.target.responseText);
xhr.open('GET', './index.html', !!'async');
xhr.send();
console.log('Esto para primero');
```

En este caso la API de `XMLHttpRequest` usa el _callback_ definido por
la función anónima cuando ha terminado.

Otro caso de API asíncrona es:

```js
var scheduling = setTimeout(() => console.log('Esto pasa después'), 1000);
console.log('Esto pasa primero')
```

Vamos a utilizar `setTimeout()` para simular APIs asíncronas que toman tiempo
de entrada y salida pero no bloquean el hilo principal:

```js
function add(a, b, onsuccess) {
  setTimeout(() => onsuccess(a + b), 1000);
}
add(21, 21, result => alert(result));
console.log('Se va a mostrar una alerta en el navegador...');
```

Ahora considera la siguiente API:

```js
function add(a, b, onsuccess) {
  setTimeout(() => onsuccess(a + b), 1000);
}
function sub(a, b, onsuccess) {
  setTimeout(() => onsuccess(a - b), 1000);
}
function mul(a, b, onsuccess) {
  setTimeout(() => onsuccess(a * b), 1000);
}
function div(a, b, onsuccess) {
  setTimeout(() => onsuccess(a / b), 1000);
}
function pow(a, b, onsuccess) {
  setTimeout(() => onsuccess(Math.pow(a, b)), 1000);
}
```

Y la siguiente operación:

```js
// (-b + sqrt(b^2-4*a*c))/(2*a)
var a = 1;
var b = -1;
var c = -2;
console.time('callback_hell');
mul(4, a, (_4a) => {
  mul(_4a, c, (_4ac) => {
    pow(b, 2, (_bb) => {
      sub(_bb, _4ac, (_discriminant) => {
        pow(_discriminant, 0.5, (sq_discriminant) => {
          add(-b, sq_discriminant, (dividend) => {
            mul(2, a, (divisor) => {
              div(dividend, divisor, (result) => {
                console.log(result);
                console.timeEnd('callback_hell');
              });
            });
          });
        });
      });
    });
  });
});
```

El ejemplo anterior es una forma de
[_callback hell_](http://callbackhell.com/), típica del modelo
de _callbacks_. La situación se hace más peliaguda si incluímos gestión de
errores.

* [Continuation passing style in JavaScript](http://delapuente.github.io/presentations/cps-javascript/index.html#/)

## Promesas

Para resolver este problema se inventaron las promesas. Las promesas
representan cómputos en el futuro. Veamos cómo pinta la función `setTimeout`
en su forma de promesa:

```js
function sleep(delay) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, delay);
  });
}
sleep(1000).then(() => console.log('Esto ocurre después'));
console.log('Esto sigue ocurriendo antes');
```

Las promesas tienen dos estados: pendiente (_pending_) y resuelta (_resolved_).
El estado resuelta tiene, a su vez, dos subestados: cumplida (_fulfillled_) y
rechazada (_rejected_). A menudo se utiliza resuelta como sinónimo de cumplida.

Cuando una promesa **se cumple, toma un resultado**. Cuando una promesa
**se rechaza, lo hace por una razon (_reason_)**.

El constructor de promesas acepta una función, llamada implementación, que
toma dos _callbacks_, uno para llamar cuando la promesa se cumpla, pasando
como parámetro el resultado, y otra para cuando la promesa se rechaza,
pasando como parámetro la razón.

Lo interesante de las promesas, no obstante, es que aplanan los _callback
hells_ con un interesante mecanismo de encadenamiento de resultados:

```js
function pow(a, b) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const result = Math.pow(a, b);
      if (isNaN(result)) {
        reject(new Error('The result of the operation is not a number'));
      }
      else {
        resolve(result);
      }
    }, 1000);
  });
}
pow(2, 2)
  .then(r => pow(r, 2))
  .then(r => pow(r, 2))
  .then(r => console.log(r));
```

También funciona si no se devuelve una promesa. En tal caso, **se construye,
implícitamente, una promesa resuelta con el valor de retorno**:

```js
pow(2, 2)
  .then(r => Math.sqrt(r))
  .then(r => console.log(r));
```

Podemos gestionar los errores, como si se tratara de un `try ... except ...`:

```js
var input = 2;
pow(input, 0.5)
  .then(r => console.log(r))
  .catch(reason => console.error(reason))
  .then(() => console.log('Other operations will continue running...'));
```

E incluso podemos re-lanzar la excepción para interrumpir la ejecución:

```js
var input = -2;
pow(input, 0.5)
  .then(r => console.log(r))
  .catch(reason => {
    console.error(reason);
    return Promise.reject(reason);
  })
  .then(() => console.log('Other operations will continue running...'));
```

Adaptar la API anterior para que haga uso de promesas:

```js
function add(a, b) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(a + b), 1000);
  });
}
function sub(a, b) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(a - b), 1000);
  });
}
function mul(a, b) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(a * b), 1000);
  });
}
function div(a, b) {
  return new Promise((resolve) => {
    setTimeout(() => resolve(a / b), 1000);
  });
}
function pow(a, b) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const result = Math.pow(a, b);
      if (isNaN(result)) {
        reject(new Error('The result of the operation is not a number'));
      }
      else {
        resolve(result);
      }
    }, 1000);
  });
}
```

Fíjate que ahora sí devolvemos cosas en cada función. Lo que devolvemos son
"promesas de los resultados". Para realizar la misma operación que antes:

```js
// (-b + sqrt(b^2-4*a*c))/(2*a)
var a = 1;
var b = -1;
var c = -2;
console.time('promises')
mul(4, a)
  .then(_4a => mul(_4a, c))
  .then(_4ac => Promise.all([_4ac, pow(b, 2)]))
  .then(([_4ac, _bb]) => sub(_bb, _4ac))
  .then(_discriminant => pow(_discriminant, 0.5))
  .catch((reason) => {
    console.log('No solution');
    return Promise.reject(reason);
  })
  .then(sq_discriminant => add(-b, sq_discriminant))
  .then(dividend => Promise.all([dividend, mul(2, a)]))
  .then(([dividend, divisor]) => div(dividend, divisor))
  .then(result => console.log(result))
  .then(() => console.timeEnd('promises'));
```

Prueba a repetir la operación con `c = 8`. ¿Qué ocurre?

La función `Promise.all()` acepta una lista de promesas y devuelve otra
promesa que se cumple cuando todas las promesas de la lista se cumplen
y como resultado proporciona una lista con los resultados de cada una de las
promesas.

Este código ya tiene gestión de errores, gracias a la función `catch()`,
que registra el error y hace fallar el resto del cómputo devolviendo
una promesa fallida con el método factoría `Promise.reject()`, que crea una
promesa rechazada.

Podríamos hacer el código un poco más asíncrono con una pequeña transformación:

```js
// (-b + sqrt(b^2-4*a*c))/(2*a)
var a = 1;
var b = -1;
var c = -2;
console.time('promises')
mul(4, a)
  .then(_4a => Promise.all([mul(_4a, c), pow(b, 2)]))
  .then(([_4ac, _bb]) => sub(_bb, _4ac))
  .then(_discriminant => pow(_discriminant, 0.5))
  .catch((reason) => {
    console.log('No solution');
    return Promise.reject(reason);
  })
  .then(sq_discriminant => Promise.all([add(-b, sq_discriminant), mul(2, a)]))
  .then(([dividend, divisor]) => div(dividend, divisor))
  .then(result => console.log(result))
  .then(() => console.timeEnd('promises'));
```

## Soporte sintáctico: async/await

El último estilo de programación asíncrona está implementado en base a una
inteligente combinación de generadores y promesas. Sin embargo, antes de
desvelar tal colaboración, veamos en qué consiste.

Existen un nuevo tipo de funciones, las funciones asíncronas, precedidas
por la palabra reservada `async`:

```js
async function pow(a, b) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const result = Math.pow(a, b);
      if (isNaN(result)) {
        reject(new Error('The result of the operation is not a number'));
      }
      else {
        resolve(result);
      }
    }, 1000);
  });
}
```

Las funciones asíncronas pueden suspender su ejecución y reanudarla por donde
iban (¿dónde hemos visto eso ya?). Para suspender su ejecución deben **esperar
por una promesa** con la palabra reservada `await`:

```js
function sleep(delay) {
  return new Promise(resolve => {
    setTimeout(resolve, delay);
  });
}

async function pow(a, b) {
  await sleep(1000);
  const result = Math.pow(a, b);
  if (isNaN(result)) {
    throw new Error('The result of the operation is not a number');
  }
  return result;
}

async function main(exp) {
  try {
    var result = await pow(-2, exp);
    console.log(result);
  }
  catch (err) {
    console.error(err);
    throw err;
  }
}

main(3);
```

Fíjate como ahora el código parece mucho más natural. La palabra reservada
`await` no solo suspende la ejecución de la función sino que además
"desenvuelve" el resultado de la promesa y lo devuelve como valor de la
expresión.

Las funciones asíncronas, también "envuelven" sus resultados en promesas,
implícitamente, para que puedan ser el objeto de expresiones `await`.

La expresión anterior es ahora muchísimo más natural:

```js
async function solve(a, b, c) {
  console.time('async/await')
  const _bb = await pow(b, 2);
  const _4ac = await mul(4, await mul(a, c));
  try {
    const sq_discriminant = await pow(await sub(_bb, _4ac), 0.5);
    const dividend = await add(-b, sq_discriminant);
    console.log(await div(dividend, await mul(2, a)));
    console.timeEnd('async/await')
  }
  catch (err) {
    console.error(err);
    throw err;
  }
  finally {
    console.timeEnd('async/await')
  }
}

solve(1, -1, -2);
```

¿Sabrías hacerlo más rápido?

```js
async function solve(a, b, c) {
  console.time('async/await')
  const [_bb, _4ac, divisor] =
    await Promise.all([pow(b, 2), mul(4, await mul(a, c)), mul(2, a)]);

  try {
    const sq_discriminant = await pow(await sub(_bb, _4ac), 0.5);
    const dividend = await add(-b, sq_discriminant);
    console.log(await div(dividend, divisor));
  }
  catch (err) {
    console.error(err);
    throw err;
  }
  finally {
    console.timeEnd('async/await')
  }
}

solve(1, -1, -2);
```
